name: vqa
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - intel-openmp=2021.4.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numpy-base=1.21.5
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.9.13
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tbb=2021.6.0
  - tzdata=2022e
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - asgiref==3.5.2
    - astunparse==1.6.3
    - av==10.0.0
    - bidict==0.22.0
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.6
    - contourpy==1.0.5
    - cycler==0.11.0
    - decord==0.6.0
    - dnspython==2.2.1
    - docker-pycreds==0.4.0
    - einops==0.5.0
    - filelock==3.8.0
    - flask==2.2.2
    - flask-cors==3.0.10
    - flask-socketio==5.3.2
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==2.0.1
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.10.1
    - idna==3.4
    - imageio==2.22.4
    - importlib-metadata==5.0.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - llvmlite==0.39.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - networkx==2.8.8
    - numba==0.56.4
    - numpy==1.23.4
    - oauthlib==3.2.2
    - onnx==1.12.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.5.1
    - pathtools==0.1.2
    - pillow==9.2.0
    - promise==2.3
    - protobuf==3.19.6
    - psutil==5.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-engineio==4.3.4
    - python-socketio==5.7.2
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scikit-video==1.1.11
    - scipy==1.9.3
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - sk-video==1.1.10
    - smmap==5.0.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-intel==2.11.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.1.1
    - thop==0.0.31-2005241907
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - timm==0.6.11
    - torch==1.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wandb==0.13.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.10.0
    - zope-event==4.5.0
    - zope-interface==5.5.2
